### ISSUE TITLE
AttributeError: 'list' object has no attribute 'get'

### ISSUE THREAD

**Issue by NicoLeOca** [ratoaq2/knowit#1]
@ratoaq2 
as my files were not PPed by Medusa because of embedded subs were not detected
I did this:

```
python -m knowit /home/nicoleoca/Downloads/AutoDL/Boardwalk.Empire.S03.1080p.BluRay.X264-ROVERS[rartv]/boardwalk.empire.s03e02.1080p.bluray.x264-rovers.mkv
For: /home/nicoleoca/Downloads/AutoDL/Boardwalk.Empire.S03.1080p.BluRay.X264-ROVERS[rartv]/boardwalk.empire.s03e02.1080p.bluray.x264-rovers.mkv
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/Medusa/lib/knowit/__main__.py", line 156, in <module>
    main(sys.argv[1:])
  File "/opt/Medusa/lib/knowit/__main__.py", line 121, in main
    knowit(videopath, options)
  File "/opt/Medusa/lib/knowit/__main__.py", line 67, in knowit
    info = api.know(video_path, vars(options))
  File "knowit/api.py", line 31, in know
    return provider.describe(video_path, options)
  File "knowit/providers/mediainfo.py", line 190, in describe
    video_tracks, audio_tracks, subtitle_tracks)
  File "knowit/provider.py", line 33, in _describe_tracks
    props = self._describe_general(general_track)
  File "knowit/provider.py", line 70, in _describe_general
    return self._describe_track(track, self.mapping['general'])
  File "knowit/provider.py", line 114, in _describe_track
    self._enrich(props, name, track, prop, context)
  File "knowit/provider.py", line 122, in _enrich
    value = source.get(prop.name) or prop.default if not is_rule else props
AttributeError: 'list' object has no attribute 'get'
```

a whole season was downloaded from the same team
a few episodes were PPed but some were not
this one above was not

here is the media info from the torrent post on Rarbg:

```
Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4.1
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 4 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 59mn 50s
Bit rate                                 : 8 942 Kbps
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 fps
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.180
Stream size                              : 3.65 GiB (84%)
Title                                    : X264
Writing library                          : x264 core 133 r2334 a3ac64b
Encoding settings                        : cabac=1 / ref=4 / deblock=1:0:0 / analyse=0x3:0x133 / me=umh / subme=7 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=0 / chroma_qp_offset=-2 / threads=36 / lookahead_threads=6 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=23 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=2pass / mbtree=1 / bitrate=8942 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / ip_ratio=1.40 / aq=1:1.00
Language                                 : English
Default                                  : Yes
Forced                                   : No

Audio
ID                                       : 2
Format                                   : DTS
Format/Info                              : Digital Theater Systems
Mode                                     : 16
Format settings, Endianness              : Big
Codec ID                                 : A_DTS
Duration                                 : 59mn 50s
Bit rate mode                            : Constant
Bit rate                                 : 1 509 Kbps
Channel(s)                               : 6 channels
Channel positions                        : Front: L C R, Side: L R, LFE
Sampling rate                            : 48.0 KHz
Frame rate                               : 93.750 fps (512 spf)
Bit depth                                : 24 bits
Compression mode                         : Lossy
Stream size                              : 646 MiB (14%)
Title                                    : DTS
Language                                 : English
Default                                  : Yes
Forced                                   : No

Text
ID                                       : 3
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Title                                    : English
Language                                 : English
Default                                  : Yes
Forced                                   : Yes
```

**Comment by NicoLeOca** [comment]
@ratoaq2 
there seems to be no embedded subtitles in the very files though
for my information, the return from Knowit above is it expected?

**Comment by ratoaq2** [comment]
can you run knowit against that file?

if you go to the lib folder, you can run
`python -m knowit path_to_your_file`

**Comment by NicoLeOca** [comment]
@ratoaq2 
I did,
you have the result above

**Comment by ratoaq2** [comment]
Sorry, I didn't notice it.
Could you run it with `--raw` ?

`python -m knowit --raw path_to_your_file`

**Comment by NicoLeOca** [comment]
Knowit 0.1.4 found:
{
    "duration": "0:57:37.131000",
    "overall_bit_rate": 9858176,
    "video": [
        {
            "number": 1,
            "language": "English",
            "duration": "0:57:37.124000",
            "size": 3523240547,
            "width": 1920,
            "height": 1080,
            "scan_type": "Progressive",
            "aspect_ratio": 1.778,
            "pixel_aspect_ratio": 1.0,
            "resolution": "1080p",
            "frame_rate": 23.976,
            "bit_rate": 8351000,
            "bit_depth": 8,
            "codec": "h264",
            "profile": "High@L4.1",
            "encoder": "x264",
            "media_type": "video/H264",
            "default": true
        }
    ],
    "audio": [
        {
            "number": 2,
            "name": "DTS",
            "language": "English",
            "duration": "0:57:37.131000",
            "size": 652101334,
            "codec": "DTS",
            "channels_count": 6,
            "channels": "5.1",
            "bit_depth": 24,
            "bit_rate": 1509000,
            "bit_rate_mode": "Constant",
            "sampling_rate": 48000,
            "compression": "Lossy",
            "default": true
        }
    ]
}

**Comment by ratoaq2** [comment]
That's not the raw output. Did you run `python -m knowit --raw path_to_your_file` inside the lib folder?

That's without raw output and the exception didn't happen.

**Comment by NicoLeOca** [comment]
oups sorry, wrong copy/paste

Knowit 0.1.4 found:
{
    "tracks": [
        {
            "count_of_menu_streams": "1",
            "writing_application": "mkvmerge v6.2.0 ('Promised Land') built on Apr 28 2013 12:22:01",
            "other_file_size": [
                "3.97 GiB",
                "4 GiB",
                "4.0 GiB",
                "3.97 GiB",
                "3.968 GiB"
            ],
            "format_version": "Version 4 / Version 2",
            "file_name": "boardwalk.empire.s03e02.1080p.bluray.x264-rovers",
            "track_type": "General",
            "file_size": 4260125521,
            "other_unique_id": [
                "239319935711834993516007413036919367612 (0xB40B57D1F81ADF8881BC5004B27927BC)"
            ],
            "format_url": "http://packs.matroska.org/",
            "format_extensions_usually_used": "mkv mk3d mka mks",
            "count_of_video_streams": "1",
            "duration": 3457131,
            "writing_library": "libebml v1.3.0 + libmatroska v1.4.0",
            "video_format_withhint_list": "AVC",
            "audio_language_list": "English",
            "stream_identifier": "0",
            "other_frame_rate": [
                "23.976 fps"
            ],
            "video_language_list": "English",
            "codec": "Matroska",
            "complete_name": "/home/nicoleoca/Downloads/AutoDL/Boardwalk.Empire.S03.1080p.BluRay.X264-ROVERS[rartv]/boardwalk.empire.s03e02.1080p.bluray.x264-rovers.mkv",
            "other_writing_library": [
                "libebml v1.3.0 + libmatroska v1.4.0"
            ],
            "other_overall_bit_rate": [
                "9 858 Kbps"
            ],
            "file_last_modification_date__local": "2016-11-18 07:48:19",
            "count_of_stream_of_this_kind": "1",
            "other_kind_of_stream": [
                "General"
            ],
            "audio_format_withhint_list": "DTS",
            "other_codec": [
                "Matroska"
            ],
            "count": "322",
            "other_stream_size": [
                "80.9 MiB (2%)",
                "81 MiB",
                "81 MiB",
                "80.9 MiB",
                "80.86 MiB",
                "80.9 MiB (2%)"
            ],
            "format": "Matroska",
            "kind_of_stream": "General",
            "other_format": [
                "Matroska"
            ],
            "file_last_modification_date": "UTC 2016-11-18 06:48:19",
            "overall_bit_rate": 9858176,
            "folder_name": "/home/nicoleoca/Downloads/AutoDL/Boardwalk.Empire.S03.1080p.BluRay.X264-ROVERS[rartv]",
            "frame_rate": "23.976",
            "codec_url": "http://packs.matroska.org/",
            "other_duration": [
                "57mn 37s",
                "57mn 37s 131ms",
                "57mn 37s",
                "00:57:37.131",
                "00:57:38;00",
                "00:57:37.131 (00:57:38;00)"
            ],
            "stream_size": 84783640,
            "video_format_list": "AVC",
            "file_extension": "mkv",
            "commercial_name": "Matroska",
            "audio_codecs": "DTS",
            "codecs_video": "AVC",
            "count_of_audio_streams": "1",
            "codec_extensions_usually_used": "mkv mk3d mka mks",
            "proportion_of_this_stream": "0.01990",
            "audio_format_list": "DTS",
            "frame_count": "82888",
            "other_writing_application": [
                "mkvmerge v6.2.0 ('Promised Land') built on Apr 28 2013 12:22:01"
            ],
            "unique_id": 239319935711834993516007413036919367612,
            "encoded_date": "UTC 2013-07-30 02:41:29"
        },
        {
            "codec_settings": "CABAC / 4 Ref Frames",
            "other_interlacement": [
                "Progressive"
            ],
            "frame_rate": "23.976",
            "sampled_height": "1080",
            "track_type": "Video",
            "stream_size": 3523240547,
            "interlacement": "PPF",
            "height": 1080,
            "other_bit_rate": [
                "8 351 Kbps"
            ],
            "bit_rate": 8351000,
            "format_settings__reframes": 4,
            "codec_id_url": "http://ffdshow-tryout.sourceforge.net/",
            "format_url": "http://developers.videolan.org/x264.html",
            "other_resolution": [
                "8 bits"
            ],
            "duration": 3457124,
            "unique_id": "1",
            "codec_settings__cabac": "Yes",
            "bits__pixel_frame": "0.168",
            "writing_library": "x264 - core 133 r2334 a3ac64b",
            "forced": "No",
            "format_info": "Advanced Video Codec",
            "stored_height": "1088",
            "codec_settings_refframes": "4",
            "width": 1920,
            "colorimetry": "4:2:0",
            "other_delay": [
                "00:00:00.000"
            ],
            "format_profile": "High@L4.1",
            "sampled_width": "1920",
            "track_id": 1,
            "delay": 0,
            "pixel_aspect_ratio": "1.000",
            "codec": "V_MPEG4/ISO/AVC",
            "other_height": [
                "1 080 pixels"
            ],
            "other_writing_library": [
                "x264 core 133 r2334 a3ac64b"
            ],
            "chroma_subsampling": "4:2:0",
            "count_of_stream_of_this_kind": "1",
            "other_kind_of_stream": [
                "Video"
            ],
            "other_language": [
                "English",
                "English",
                "en",
                "eng",
                "en"
            ],
            "other_codec": [
                "AVC"
            ],
            "format_settings__cabac": "Yes",
            "other_frame_rate_mode": [
                "Constant"
            ],
            "color_space": "YUV",
            "other_stream_size": [
                "3.28 GiB (83%)",
                "3 GiB",
                "3.3 GiB",
                "3.28 GiB",
                "3.281 GiB",
                "3.28 GiB (83%)"
            ],
            "kind_of_stream": "Video",
            "format": "AVC",
            "streamorder": "0",
            "codec_info": "Advanced Video Codec",
            "other_format_settings__reframes": [
                "4 frames"
            ],
            "scan_type": "Progressive",
            "delay__origin": "Container",
            "internet_media_type": "video/H264",
            "stream_identifier": "0",
            "display_aspect_ratio": "1.778",
            "other_bit_depth": [
                "8 bits"
            ],
            "codec_url": "http://ffdshow-tryout.sourceforge.net/",
            "other_width": [
                "1 920 pixels"
            ],
            "format_settings": "CABAC / 4 Ref Frames",
            "other_track_id": [
                "1"
            ],
            "other_duration": [
                "57mn 37s",
                "57mn 37s 124ms",
                "57mn 37s",
                "00:57:37.124",
                "00:57:38;00",
                "00:57:37.124 (00:57:38;00)"
            ],
            "count": "332",
            "other_delay__origin": [
                "Container"
            ],
            "commercial_name": "AVC",
            "encoded_library_version": "core 133 r2334 a3ac64b",
            "frame_rate_mode": "CFR",
            "language": "en",
            "default": "Yes",
            "frame_count": "82888",
            "other_forced": [
                "No"
            ],
            "title": "X264",
            "bit_depth": 8,
            "encoding_settings": "cabac=1 / ref=4 / deblock=1:0:0 / analyse=0x3:0x133 / me=umh / subme=7 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=0 / chroma_qp_offset=-2 / threads=36 / lookahead_threads=6 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=23 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=2pass / mbtree=1 / bitrate=8351 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / ip_ratio=1.40 / aq=1:1.00",
            "other_scan_type": [
                "Progressive"
            ],
            "encoded_library_name": "x264",
            "other_format_settings__cabac": [
                "Yes"
            ],
            "codec_profile": "High@L4.1",
            "codec_id": "V_MPEG4/ISO/AVC",
            "other_frame_rate": [
                "23.976 fps"
            ],
            "proportion_of_this_stream": "0.82703",
            "resolution": 8,
            "other_default": [
                "Yes"
            ],
            "other_display_aspect_ratio": [
                "16:9"
            ],
            "codec_family": "AVC"
        },
        {
            "other_channel_s": [
                "6 channels"
            ],
            "track_type": "Audio",
            "stream_size": 652101334,
            "other_channel_positions": [
                "3/2/0.1"
            ],
            "resolution": 24,
            "other_compression_mode": [
                "Lossy"
            ],
            "other_bit_rate": [
                "1 509 Kbps"
            ],
            "bit_rate": 1509000,
            "other_resolution": [
                "24 bits"
            ],
            "duration": 3457131,
            "bit_rate_mode": "CBR",
            "other_bit_depth": [
                "24 bits"
            ],
            "forced": "No",
            "samples_per_frame": "512",
            "format_info": "Digital Theater Systems",
            "title": "DTS",
            "other_frame_rate": [
                "93.750 fps (512 spf)"
            ],
            "channel_positions": "Front: L C R, Side: L R, LFE",
            "format_settings__endianness": "Big",
            "track_id": 2,
            "delay": 0,
            "codec": "DTS",
            "sampling_rate": 48000,
            "count_of_stream_of_this_kind": "1",
            "other_kind_of_stream": [
                "Audio"
            ],
            "other_language": [
                "English",
                "English",
                "en",
                "eng",
                "en"
            ],
            "other_codec": [
                "DTS"
            ],
            "count": "272",
            "other_stream_size": [
                "622 MiB (15%)",
                "622 MiB",
                "622 MiB",
                "622 MiB",
                "621.9 MiB",
                "622 MiB (15%)"
            ],
            "other_video0_delay": [
                "00:00:00.000"
            ],
            "format": "DTS",
            "kind_of_stream": "Audio",
            "delay__origin": "Container",
            "bit_depth": 24,
            "stream_identifier": "0",
            "frame_rate": "93.750",
            "delay_relative_to_video": 0,
            "other_track_id": [
                "2"
            ],
            "other_duration": [
                "57mn 37s",
                "57mn 37s 131ms",
                "57mn 37s",
                "00:57:37.131",
                "00:57:37.131"
            ],
            "other_sampling_rate": [
                "48.0 KHz"
            ],
            "other_delay__origin": [
                "Container"
            ],
            "commercial_name": "DTS",
            "channellayout": "C L R Ls Rs LFE",
            "language": "en",
            "default": "Yes",
            "other_bit_rate_mode": [
                "Constant"
            ],
            "other_delay_relative_to_video": [
                "00:00:00.000"
            ],
            "other_default": [
                "Yes"
            ],
            "channel_s": 6,
            "streamorder": "1",
            "mode": "16",
            "codec_id": "A_DTS",
            "other_delay": [
                "00:00:00.000"
            ],
            "compression_mode": "Lossy",
            "proportion_of_this_stream": "0.15307",
            "video0_delay": 0,
            "samples_count": "165942288",
            "other_forced": [
                "No"
            ],
            "unique_id": "18267323022949817998",
            "codec_family": "DTS"
        },
        {
            "count": "98",
            "00_01_38515": "en:00:01:38.515",
            "stream_identifier": "0",
            "00_56_20210": "en:00:56:20.210",
            "chapters_pos_begin": "90",
            "track_type": "Menu",
            "kind_of_stream": "Menu",
            "00_08_34305": "en:00:08:34.305",
            "chapters_pos_end": "98",
            "00_26_41892": "en:00:26:41.892",
            "00_17_26712": "en:00:17:26.712",
            "00_00_00000": "en:00:00:00.000",
            "00_46_13562": "en:00:46:13.562",
            "00_35_19743": "en:00:35:19.743",
            "other_kind_of_stream": [
                "Menu"
            ],
            "count_of_stream_of_this_kind": "1"
        }
    ]
}

**Comment by ratoaq2** [comment]
I can't reproduce that error. When you run without `--raw` it should consistently give you that error, correct?

I'm using your raw input to simulate it here and it just works, no exception is raised.

**Comment by NicoLeOca** [comment]
no it's not consistent
I just run it 10 times and it never failed

**Comment by ratoaq2** [comment]
Ok, I was able to reproduce it changing your raw output to not have a "track_type: General" and I spot the issue. But I can't tell why that's not consistent.

**Comment by NicoLeOca** [comment]
how can I help?

**Comment by ratoaq2** [comment]
I'm fixing this issue, the exception shouldn't occur. Let's wait and see if you'll face inconsistency problems after this fix.

**Comment by NicoLeOca** [comment]
ok thank you @ratoaq2 
knowit is a great benefit; I am looking forward to see it fully integrated into Medusa
