### ISSUE TITLE
subprocess.CalledProcessError

### ISSUE THREAD

**Issue by labrys** [ratoaq2/knowit#11]
Running knowit on a file results in an uncaught `subprocess.CalledProcessError` for `ffprobe`.

Running `ffprobe` manually on the file results in 
```
Format matroska,webm detected only with low score of 1, misdetection possible!
EBML header parsing failed
.\video.mkv: Invalid data found when processing input
```
The file is likely corrupted/invalid but the error should still be caught and/or a specific application error raised.

**Comment by ratoaq2** [comment]
The library since last releases raises a KnowitException instead
