### ISSUE TITLE
Any plan to create a new release?

### ISSUE THREAD

**Issue by morpheus65535** [ratoaq2/knowit#136]
It's been <s>almost</s> over a year now and some fixes would be happily merged into Bazarr. Thanks @ratoaq2 !

**Comment by ratoaq2** [comment]
Yes, I'll try to make a release soon

**Comment by ratoaq2** [comment]
https://github.com/ratoaq2/knowit/releases/tag/0.5.3

**Comment by morpheus65535** [comment]
Thanks!
