### ISSUE TITLE
Knowit fails to detect MediaInfo.dll

### ISSUE THREAD

**Issue by labrys** [ratoaq2/knowit#14]
With a default installation of `MediaInfo` on Windows, `knowit` fails to detect the `.dll` and falls back on the `MediaInfo.exe` GUI.  This is problematic in a script as it causes the `MediaInfo` GUI to pop up on each usage.

Windows 10
MediaInfo v18.05 x64 GUI
Python 3.7.0
knowit fd3d0e0ab85314619db13b10e5e84505884e7128

**Comment by ratoaq2** [comment]
@labrys Are you able to confirm if this problem still happens with latest master?

**Comment by labrys** [comment]
I'll test it this weekend

**Comment by ratoaq2** [comment]
It's a pitty MediaInfo provides the GUI and the CLI under the same name.

I enhanced a bit mediainfo provider to skip potential GUI executables: Only test the executable if it doesn't have an icon
