### ISSUE TITLE
Knowit not suited for pickling

### ISSUE THREAD

**Issue by p0psicles** [ratoaq2/knowit#15]
Hi @ratoaq2 
I'm having issues dogpiling knowit results, because it has al kinds of non-pickable objects, like datetime, Quantity, etc.

I'm currenlty trying dogpile with msgpack writing my own encoders. But it's really a hassle.

What would be your approach here?

**Comment by p0psicles** [comment]
One of the issues I have with the knowit results, is that the reporter is using different object reported by different providers. It would be really nice if this could be standardized. Any reason why this hasn't been done?

**Comment by ratoaq2** [comment]
I still didn't get the different object reported by different providers

**Comment by p0psicles** [comment]
Check this: https://github.com/pymedusa/Medusa/pull/5135/files#diff-8dae95e92447489197bc2654f723edaeR106. You see that I already encode a number of non-pickable object types. Like for example `babelfish.Language` and `from pint.quantity import _Quantity`. Those are not `generic` dogpile reported objects. Which I would expect. I would expect that for Quantity it would always use this: `from knowit.properties import Language, Quantity`. But that's not the case.

I didn't make these up. I had to add them by trial an error. And it worked to some degree.

Unfortunately, i'm digging into something else right now. And this didn't have a very high prio for me at the time.

**Comment by ratoaq2** [comment]
no_units is an option that's available since long time. That will get rid of pint Quantity

**Comment by ratoaq2** [comment]
Fixed by [c9b7177](https://github.com/ratoaq2/knowit/commit/c9b7177466a01be2c9be9a519c486e7c94ac5d63)

**Comment by p0psicles** [comment]
Aah thx. Then we can start dogpile cache the knowit results.
