### ISSUE TITLE
Problem in docker (medusa) WARNING  SHOWQUEUE-ADD :: [] An error occurred while parsing

### ISSUE THREAD

**Issue by DAVIZINH0** [ratoaq2/knowit#19]
**Describe the bug**
Hello, i have medusa in docker with a synology and i have a problem when i add any tvshow.
Not special configuration.
not ocurrs with all chapters and all have the same format.
It happens with official docker repository and de linuxserver repository
Appears the warning that i put in the log

**To Reproduce**
Fress install in docker

**Expected behavior**
no warnings

**Medusa (please complete the following information):**
OS: synology DSM and DOCKER. 
Linux-4.4.59+-x86_64-with
Branch: master
Commit: Unknown
Version: 0.3.2
Database: 44.14
Python Version: | 2.7.16 (default, May  6 2019, 19:35:26)  [GCC 8.3.0]

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
2019-06-07 17:37:57 WARNING  SHOWQUEUE-ADD :: [] An error occurred while parsing: /series/American Gods/Temporada 1/American Gods - 1x01 - La plantación de huesos.mkv
KnowIt reported:
+-------------------------------------------------------+
|                   KnowIt 0.3.0-dev                    |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                          4.0                          |
|                   libmediainfo.so.0                   |
|                        v18.8.1                        |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "/app/medusa/ext/knowit/api.py", line 64, in know
    result = provider.describe(video_path, context)
  File "/app/medusa/ext/knowit/providers/mediainfo.py", line 285, in describe
    media_info = self.executor.extract_info(video_path)
  File "/app/medusa/ext/knowit/providers/mediainfo.py", line 100, in extract_info
    return self._execute(filename)
  File "/app/medusa/ext/knowit/providers/mediainfo.py", line 167, in _execute
    return MediaInfo.parse(filename, library_file=self.location)
  File "/app/medusa/lib/pymediainfo/__init__.py", line 296, in parse
    " with libmediainfo".format(filename))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 68: ordinal not in range(128)

+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+
2019-06-07 17:37:56 WARNING  SHOWQUEUE-ADD :: [] An error occurred while parsing: /series/American Gods/Temporada 1/American Gods - 1x08 - Ven a Jesús.mkv
KnowIt reported:
+-------------------------------------------------------+
|                   KnowIt 0.3.0-dev                    |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                          4.0                          |
|                   libmediainfo.so.0                   |
|                        v18.8.1                        |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "/app/medusa/ext/knowit/api.py", line 64, in know
    result = provider.describe(video_path, context)
  File "/app/medusa/ext/knowit/providers/mediainfo.py", line 285, in describe
    media_info = self.executor.extract_info(video_path)
  File "/app/medusa/ext/knowit/providers/mediainfo.py", line 100, in extract_info
    return self._execute(filename)
  File "/app/medusa/ext/knowit/providers/mediainfo.py", line 167, in _execute
    return MediaInfo.parse(filename, library_file=self.location)
  File "/app/medusa/lib/pymediainfo/__init__.py", line 296, in parse
    " with libmediainfo".format(filename))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfa' in position 66: ordinal not in range(128)

+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+
```
</details>

**Comment by medariox** [comment]
Only occurring with `pymediainfo >= 4.0`.

**Comment by 9Rune5** [comment]
I have the same problem. It flat out refuses to deal with any path containing international characters.

**Comment by Beanux** [comment]
Same here, when having non ascii characteres.
It prevent Medusa to parse and to rename when the the destination name is not ascii (like in french in my case, but surely spanish, italian or german).

**Comment by m1dnight** [comment]
Same here:

`2019-12-03 11:22:57 WARNING  SHOWQUEUE-ADD :: [] An error occurred while parsing: /series/90 Day Fiancé/Season 06/90 Day Fiancé - S06E06 - Flirting with Disaster.mkv`

and 

`2019-12-03 11:10:36 WARNING  SHOWQUEUE-ADD :: [] An error occurred while parsing: /series/Superstore/Season 04/Superstore - S04E17 - Quinceañera.mkv`

**Comment by Tailslide** [comment]
Having the same issue under medusa on a synology system.

`+-------------------------------------------------------+
|                   KnowIt 0.3.0-dev                    |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                         3.2.1                         |
|      /usr/local/mediainfo/lib/libmediainfo.so.0       |
|                         v19.9                         |
|                                                       |
|             /usr/local/ffmpeg/bin/ffprobe             |
|                        v4.2.2                         |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/api.py", line 64, in know
    result = provider.describe(video_path, context)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/providers/mediainfo.py", line 285, in describe
    media_info = self.executor.extract_info(video_path)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/providers/mediainfo.py", line 100, in extract_info
    return self._execute(filename)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/providers/mediainfo.py", line 167, in _execute
    return MediaInfo.parse(filename, library_file=self.location)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/pymediainfo/__init__.py", line 266, in parse
    " with libmediainfo".format(filename))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 87: ordinal not in range(128)

+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+`

**Comment by medariox** [comment]
Python version?

**Comment by Tailslide** [comment]
I have V3.5.1 and V2.7.12 installed but I believe the medusa package for synology forces python 2 to be used.

**Comment by 9Rune5** [comment]
@Tailslide there is an unofficial package that will install medusa with python 3. IIRC I got mine from https://github.com/SynoCommunity/spksrc/issues/3710#issuecomment-524808904

Backup your config first... I do not remember having any difficulties getting up and running again. (and a newer python does solve this issue afaict)

**Comment by Tailslide** [comment]
@9Rune5 thanks I just grabbed that and might give it a shot if I start having more python2 related problems.  Hopefully the official package winds up getting updated at some point.

**Comment by ratoaq2** [comment]
python 2 is not anymore supported
