### ISSUE TITLE
MediaInfo tests fail with MediaInfo >= 18.08

### ISSUE THREAD

**Issue by labrys** [ratoaq2/knowit#33]
MediaInfo fail during all tests for `video.codec`, `video.profile`, `video.profile_level`, `audio.codec`, and `audio.profile`:

```
video[0].codec: Expected H.264 got None
video[0].profile: Expected Main got None
video[0].profile_level: Expected 3.1 got None
audio[0].codec: Expected AAC got None
audio[0].profile: Expected Low Complexity got None
```

Tested with `MediaInfo.dll` versions:
- 18.08
- 18.08.1
- 18.12
- 19.04
- 20.09

Tested with `MediaInfo.exe` CLI versions:
- 20.09

**Comment by ratoaq2** [comment]
https://github.com/MediaArea/MediaInfoLib/tree/v17.10

Probably this was the backwards incompatible release. I'll need some free time to look at it. 
Also need to drop support for old python versions, and have a proper new release.

**Comment by labrys** [comment]
It is the backwards incompatible release of MediaInfo.  MediaInfo no longer has the previous versions available on their website.   Any affected users who want to install older versions of MediaInfo on Windows can install them with Chocolatey.

**Comment by ratoaq2** [comment]
Latest knowit release already handles this issue properly
