### ISSUE TITLE
Fails to run on Python 3.10 due to AttributeError

### ISSUE THREAD

**Issue by labrys** [ratoaq2/knowit#35]
Trying to run on Python 3.10 causes an attribute error due to [babelfish](https://pypi.org/project/babelfish/) having abstract base classes imported from `collections` instead of `collections.abc`.  This has already been fixed upstream (https://github.com/Diaoul/babelfish/issues/29) and is waiting on a new babelfish release to be pushed to pypi (https://github.com/Diaoul/babelfish/issues/33).

**Comment by ratoaq2** [comment]
knowit now depends on babelfish = "^0.6.0"
