### ISSUE TITLE
Feature request: Detect audio language

### ISSUE THREAD

**Issue by OmgImAlexis** [ratoaq2/knowit#4]
Not sure if this is out of scope for this library but it'd be great if this could detect the correct language for the audio track.

My main idea with this is the grab the audio track from the container, run it through speech recognition and then send the text from that to Python's language detection library.

The main use for this would be so an external library can then edit the container and set the audio track to have a name for the language instead of having "und", this would be helpful with container that have multiple tracks of "und" audio.

**Comment by ratoaq2** [comment]
Yeah, this is indeed outside of the scope of this low level tool. 
This tool responsibility is only to parse video metadata present in the media file
