### ISSUE TITLE
Error Occured while parsing What If… - 1x02 - What If… T’Challa Became a Star-Lord.mkv

### ISSUE THREAD

**Issue by WarEagleUS21** [ratoaq2/knowit#40]
**Seems like my scene exceptions to make this show parse and show in Medusa isn't working and caused this error (not a problem but it is going to affecting parsing future episodes even though it grabbed the first one no problem)**

### 2021-08-19 06:13:01 WARNING  SHOWQUEUE-REFRESH :: [fbd43ad] An error occurred while parsing: L:\TV Shows\What If\Season 1\What If… - 1x02 - What If… T’Challa Became a Star-Lord.mkv
KnowIt reported:
+-------------------------------------------------------+
|                   KnowIt 0.3.0-dev                    |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                         3.2.1                         |
| edusa\Medusa\lib\native\windows\x86_64\MediaInfo.dll  |
[Debug Log What IF.txt](https://github.com/ratoaq2/knowit/files/7013988/Debug.Log.What.IF.txt)
[Debug Log What IF.zip](https://github.com/ratoaq2/knowit/files/7013989/Debug.Log.What.IF.zip)

|                        v0.7.89                        |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "C:\Medusa\Medusa\ext\knowit\api.py", line 64, in know
    result = provider.describe(video_path, context)
  File "C:\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 285, in describe
    media_info = self.executor.extract_info(video_path)
  File "C:\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 100, in extract_info
    return self._execute(filename)
  File "C:\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 167, in _execute
    return MediaInfo.parse(filename, library_file=self.location)
  File "C:\Medusa\Medusa\lib\pymediainfo\__init__.py", line 266, in parse
    " with libmediainfo".format(filename))
RuntimeError: An eror occured while opening L:\TV Shows\What If\Season 1\What If… - 1x02 - What If… T’Challa Became a Star-Lord.mkv with libmediainfo

+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+

**Comment by ratoaq2** [comment]
Upgrade to latest knowit and report back if the issue persists

**Comment by WarEagleUS21** [comment]
Will do. Thank you

**Comment by WarEagleUS21** [comment]
Well it looks like I can't upgrade Knowit as I am not finding a zip or exe package for it. Looks like this came with Medusa and that is on the latest masterbuild.

**Comment by WarEagleUS21** [comment]
Figured it out. Wil report back (reopen) if the issue pops back up.
