### ISSUE TITLE
Detecting "source" of video file

### ISSUE THREAD

**Issue by pannal** [ratoaq2/knowit#6]
Hey,

I'm sure you've had this line of thought as well, before. Can you think of a way to "guess"/"detect" the source of a video file such as HDTV, BluRay, WEB-DL?

In Sub-Zero many users don't include any source or release group info in their file names, making it hard to match subtitles.

Could it be possible to guess the source by looking at metadata attributes such as FPS and audio format?

Thank you.

**Comment by ratoaq2** [comment]
I don't think there's a reliable way to go that. 
:-/

**Comment by pannal** [comment]
That's disappointing, but thank you :)
